// 

export const portfolio = [
  {
    id: "carrot",
    title:
      "Designing Carrot: An App That Lets You Borrow From Your Stocks without Selling Them.",
    text: [
      "In an era where financial inclusion and accessible credit remain pressing challenges across emerging markets, the rise of digital financial services has opened new doors for innovation. Yet, traditional lending models often fail to serve the growing number of retail investors who have assets but lack access to instant, low-friction credit. As more people invest in stocks and digital assets, there’s a growing need to unlock the value of these portfolios in smarter, more flexible ways.",
      "Carrot was founded to meet this need—reimagining credit by turning investment portfolios into accessible collateral. Through strategic partnerships with investment platforms, Carrot provides users with an instant line of credit based on the value of their holdings. By placing a lien on their portfolio and issuing loans with transparent interest structures, Carrot empowers users to borrow responsibly without selling off their assets.",
      "More than just a lending platform, Carrot reflects a shift toward a new kind of financial infrastructure—one that is API-first, user-centric, and deeply integrated with the habits of modern investors. In doing so, it not only helps users unlock liquidity but also reshapes how credit works in the age of digital finance.",
    ],
    fullCaseLink:
      "https://kingsleyukeje.notion.site/Designing-Carrot-An-App-That-Lets-You-Borrow-From-Your-Stocks-without-Selling-Them-fbd7ce0185a3448c97536e02226c5f38?source=copy_link",
    otherResources: [
      {
        id: 1,
        title: "organization",
        description: "carrotcredit",
      },
      {
        id: 2,
        title: "sector",
        description: "financial technology",
      },
      {
        id: 3,
        title: "motion designer",
        description: "samuel olaniyi",
        link: "https://www.linkedin.com/in/samuel-olaniyi/",
      },
      {
        id: 4,
        title: "role",
        description: "lead designer",
      },
      {
        id: 5,
        title: "platform",
        description: "website, mobile app & web app",
      },
      {
        id: 6,
        title: "live project",
        description: "carrotcredit",
        link: "https://www.carrotcredit.com/",
      },
      {
        id: 7,
        title: "case study",
        description: "read full case study",
        link: "https://kingsleyukeje.notion.site/Designing-Carrot-An-App-That-Lets-You-Borrow-From-Your-Stocks-without-Selling-Them-fbd7ce0185a3448c97536e02226c5f38?source=copy_link",
      },
    ],
    portfolioImages: [
      ["1"],
      ["2"],
      ["3"],
      ["4"],
      ["5", "6"],
      ["7", "8"],
      ["9", "10"],
      ["11", "12"],
      ["13", "14"],
      ["15"],
      ["16"],
      ["17"],
      ["18"],
      ["19"],
      ["20"],
      ["21"],
      ["22"],
      ["23", "24"],
      ["25"],
      ["26"],
    ],
    textsMargin: false,
    studyMargin: true,
  },
  {
    id: "eze",
    title:
      "Creating a Scalable Platform to Meet the Growing Demand for Affordable and Sustainable Electronics",
    text: [
      "During the Apple WWDC event of 2023, when the iPhone 15 series was announced, a major part of their event was centred around their sustainability efforts, focusing on reducing their carbon footprint and moving towards greener manufacturing processes for electronic devices. This commitment to sustainability reflects a broader shift in the industry, with consumers becoming more conscious of the lifecycle of their electronics and businesses increasingly looking for ways to align with these values.",
      "The rapid innovation cycle and planned obsolescence of smartphones have produced a growing secondary smartphone market. Whether you’re an individual trading in his or her own personal cellphone, or a vendor buys and sells smartphones in large volumes, navigating the used electronics space is difficult",
      "Eze Wholesale was founded to address this need: to create a streamlined, efficient platform where businesses can access bulk electronics, including refurbished devices, directly from trusted suppliers. By facilitating access to pre-owned devices and reducing reliance on new product manufacturing, Eze Wholesale not only helps businesses lower costs but also contributes to the broader push for sustainability by extending the lifecycle of electronics.",
    ],
    fullCaseLink:
      "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
    otherResources: [
      {
        id: 1,
        title: "organization",
        description: "ezewholesale",
      },
      {
        id: 2,
        title: "sector",
        description: "eCommerce, Supply Chain",
      },
      {
        id: 3,
        title: "motion designer",
        description: "samuel olaniyi",
        link: "https://www.linkedin.com/in/samuel-olaniyi/",
      },
      {
        id: 4,
        title: "role",
        description: "lead designer",
      },
      {
        id: 5,
        title: "platform",
        description: "website, mobile app & web app",
      },
      {
        id: 6,
        title: "live project",
        description: "eze wholesale",
        link: "https://ezewholesale.com/",
      },
      {
        id: 7,
        title: "case study",
        description: "read full case study",
        link: "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
      },
    ],
    portfolioImages: [
      ["1"],
      ["2"],
      ["3"],
      ["4"],
      ["5", "6"],
      ["7", "8"],
      ["9"],
      ["10", "11"],
      ["12"],
      ["13"],
      ["14"],
      ["15"],
      ["16", "17"],
      ["18", "19"],
      ["20", "21"],
      ["22"],
      ["23"],
      ["24"],
      ["25"],
      ["26"],
    ],
    textsMargin: false,
    studyMargin: false,
  },
  {
    id: "spasora",
    title:
      "Building a Scalable Platform to Meet Growing Demand for Flexible and Sustainable Spaces",
    text: [
      "During COVID break, shifts in the workspace and creative industries highlighted a growing focus on sustainability, resource efficiency, and maximizing the value of existing assets. Hosts and property owners are becoming increasingly aware of the importance of reducing idle time and ensuring their spaces are fully utilized, while also providing quality experiences for users.",
      "Spasora was designed to meet this need: a simple, efficient platform where hosts can list their spaces, and businesses, creators, and event organizers can discover, filter, and book them directly. By optimizing space utilization and providing access to existing venues, Spasora not only helps hosts generate additional revenue but also supports sustainability by making better use of current spaces instead of requiring new constructions.",
      "In addition, Spasora empowers hosts with tools to manage availability, communicate with guests, and maintain high-quality standards, creating a more professional and trusted environment for both sides. This ensures that every booking is seamless, predictable, and aligned with the evolving expectations of modern users.",
    ],
    fullCaseLink:
      "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
    otherResources: [
      {
        id: 1,
        title: "organization",
        description: "Spasora",
      },
      {
        id: 2,
        title: "sector",
        description: "Online Bookings, Space Network, Proptech",
      },
      // {
      //   id: 3,
      //   title: "motion designer",
      //   description: "samuel olaniyi",
      //   link: "https://www.linkedin.com/in/samuel-olaniyi/",
      // },
      {
        id: 4,
        title: "role",
        description: "lead designer",
      },
      {
        id: 5,
        title: "platform",
        description: "website, mobile app & web app",
      },
      {
        id: 6,
        title: "live project",
        description: "Shutdown Operations",
        // link: "https://ezewholesale.com/",
      },
      {
        id: 7,
        title: "case study",
        description: "read full case study",
        link: "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
      },
    ],
    portfolioImages: [
      ["1", "2"],
      ["3", "4"],
      ["5", "6"],
      ["7"],
      ["8", "9"],
      ["10", "11"],
      ["12"],
      ["13"],
      ["14", "15"],
      ["16"],
      ["17"],
      ["18"],
      ["19"],
      ["20"],
      ["21"],
      ["22"],
      ["23"],
      ["24"],
      ["25"],
      ["26"],

    ],
    textsMargin: true,
    studyMargin: false,
  },
  {
    id: "hotelng",
    title:
      "Building a Scalable Booking Platform to Meet the Growing Demand for Affordable Hotel Stays Across Africa",
    text: [
      "As travel and mobility continue to grow across Nigeria, affordability and reliability have become top priorities for travellers. Consumers are increasingly price-sensitive, while hotels are looking for better digital channels to reach demand without heavy overhead. Finding and booking hotels in Africa is often fragmented. Travellers struggle with inconsistent pricing, poor availability data, and limited trust. On the other side, many hotels—especially small and mid-sized ones—lack efficient tools to distribute their inventory at scale.",
      "Hotels.ng was built to bridge this gap by creating a centralized, scalable platform that connects travellers directly with verified hotels nationwide. By aggregating hotel inventory and standardizing booking experiences, the platform simplifies discovery, improves trust, and expands access to affordable accommodation.",
      "For travellers, this means easier access to reliable, budget-friendly stays. For hotels, it means increased visibility, higher occupancy, and reduced dependence on offline or manual booking processes—supporting a more efficient and sustainable hospitality ecosystem.",
    ],
    fullCaseLink:
      "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
    otherResources: [
      {
        id: 1,
        title: "organization",
        description: "Hotels NG",
      },
      {
        id: 2,
        title: "sector",
        description: "Travel, Hospitality, Proptech",
      },
      {
        id: 3,
        title: "motion designer",
        description: "namnso ukpanah",
        link: "https://www.linkedin.com/in/samuel-olaniyi/",
      },
      {
        id: 4,
        title: "role",
        description: "team designer",
      },
      {
        id: 5,
        title: "platform",
        description: "website, mobile app & web app",
      },
      {
        id: 6,
        title: "live project",
        description: "hotels.ng",
        link: "https://ezewholesale.com/",
      },
      {
        id: 7,
        title: "case study",
        description: "read full case study",
        link: "https://kingsleyukeje.notion.site/Creating-a-Scalable-Platform-to-Meet-the-Growing-Demand-for-Affordable-and-Sustainable-Electronics-86bdc6c8155e4691a6aa8c913f7e480f?source=copy_link",
      },
    ],
    portfolioImages: [
      ["1"],
      ["2"],
      ["3"],
      ["4"],
      ["5", "6"],
      ["7", "8"],
      ["9"],
      ["10", "11"],
      ["12"],
      ["13"],
      ["14"],
      ["15"],
      ["16", "17"],
      ["18", "19"],
      ["20", "21"],
      ["22"],
      ["23"],
      ["24"],
      ["25"],
      ["26"],

    ],
    textsMargin: true,
    studyMargin: false,
  },
];